@startuml

interface   IAdministrator
{
    int rename(IUser&, string name)
    int mute(IUser&)
    int kick(IUser&)
    int ban(IUser&)
}

class   Administrator
{
    int permission
}

IAdministrator <|-- Administrator

enum   Mode
{
    i
    t
    k
    o
    l
}

interface   IUser
{
    int rename(string name)
}

class   User
{
    string      username
    string      nickname
    Role        role
    bool        isOps
}

class   Channel
{
    string          name
    unsigned int    userLimit
    bool            inviteOnly
    Mode            mode
    
    
}

class   Server
{
    string          serverName
    unsigned int    port
    string          password
    list<IUser>     users
    list<Channel>   channels
    
    int disconnect(IUser&)
    int kick(IUser&)
    int ban(IUser&)
}

Server *-- Channel

IUser <|-- User

@enduml
