@startuml

interface   IAdministrator
{
    int rename(IUser&, string name)
    int mute(IUser&)
    int kick(IUser&)
    int ban(IUser&)
}

class   Administrator
{
    int permission
}

IAdministrator <|-- Administrator

abstract   ARole
{
    int id;
    string  name;
    int permission
}

class   Role

interface   IUser
class   User
{
    string      username
    list<ARole> role
}

class   Server
{
    string  serverID
    list<IUser> users
    
    int disconnect(IUser&)
    int kick(IUser&)
    int ban(IUser&)
    i
}

ARole <|-- Role

IUser <|-- User

@enduml
